### PR TITLE
[polkit] Update to 125. JB#61306

### PR DESCRIPTION
**Pull request by pvuorela**
We can finally update now that mozjs is no longer a hard dependency.

Removed all the external patching from e.g. Debian used for maintaining an ancient version.

Dropped also the old changelog. No much need and contained some bogus date.

---
Depends on duktape: https://github.com/pvuorela/duktape 

The project was a bit hostile towards building from git: the current 2.x series has a python2 build setup script, requiring also python2-yaml, that does some makefile / source file adjustments. Master has support for python 3 but did it by making the file a wrapper for some node.js thing. So, eh, just did a dumb package.

### CODE REVIEW

**Review by spiiroin — APPROVED** [review]

**Review by direc85 — APPROVED** [review]
LGTM

Great to see upstream reached now and all the old patches gone!

I tested this on my dev device, and pkcon waits for permission, but as that requires lipstick changes, nothing happens - at the time of writing, this is expected.

**Comment by Thaodan** [comment]
I think we should bootstrap the sources on a host and then only checkin the generated sources plus git submodule instead of tracking binary blobs into git.

An example script can be found in the ruby package: 
https://github.com/sailfishos/ruby/blob/master/rpm/generate_bootstrap.sh

The script would need python2 installed and then setup a virtual environment with pipx.

**Comment by pvuorela** [comment]
> I think we should bootstrap the sources on a host and then only checkin the generated sources plus git submodule instead of tracking binary blobs into git.

I assume you're talking about duktape. I wouldn't say there are binary blobs involved, not counting the source tar ball as such.

Yea, generating the sources outside the build environment and storing them on another place could be an option, but it's also getting a bit complicated doing these virtual environments, and then there's the node.js switch also coming up. We can revisit the packaging if there's a need. Maybe after the 3.x release.

**Comment by Thaodan** [comment]
> > I think we should bootstrap the sources on a host and then only checkin the generated sources plus git submodule instead of tracking binary blobs into git.
> 
> I assume you're talking about duktape. I wouldn't say there are binary blobs involved, not counting the source tar ball as such.

Yes I do, should have mentioned that. The tarball does count as a binary blob to git, we are discouraged to upload blobs to Git as it increases storage space used by repositories  very much.

> Yea, generating the sources outside the build environment and storing them on another place could be an option, but it's also getting a bit complicated doing these virtual environments, and then there's the node.js switch also coming up. We can revisit the packaging if there's a need. Maybe after the 3.x release.

I think you might misunderstand me: There isn't literally a virtual environment just one in pip so it doesn't touch anything else.
The process is the same with neither python or nodejs.

**Comment by direc85** [comment]
With updated lipstick pkcon now asks permission as expected.

**Comment by pvuorela** [comment]
> Yes I do, should have mentioned that. The tarball does count as a binary blob to git, we are discouraged to upload blobs to Git as it increases storage space used by repositories very much.

Some blobs is business as usual, think of image files etc. Big files is another thing. This ain't a big file.

> I think you might misunderstand me: There isn't literally a virtual environment just one in pip so it doesn't touch anything else.
> The process is the same with neither python or nodejs.

I got it, but it's still some special tooling more.

Tried checking pip (without x) a bit. Doesn't immediately appear that nicely supported installing python2 packages at this point. The tool itself is not supported on python2 anymore and I think the python3 version just wants to install python3 modules(?) Assuming pipx is the same thing.

**Review by mlehtima — APPROVED** [review]

**Comment by Thaodan** [comment]
Pekka Vuorela ***@***.***> writes:

>> Yes I do, should have mentioned that. The tarball does count as a
>> binary blob to git, we are discouraged to upload blobs to Git as it
>> increases storage space used by repositories very much.
>
> Some blobs is business as usual, think of image files etc. Big files is another thing. This ain't a big file.
>
>> I think you might misunderstand me: There isn't literally a virtual environment just one in pip so it doesn't touch anything else.
>> The process is the same with neither python or nodejs.
>
> I got it, but it's still some special tooling more.
>
> Tried checking pip (without x) a bit. Doesn't immediately appear that
> nicely supported installing python2 packages at this point. The tool
> itself is not supported on python2 anymore and I think the python3
> version just wants to install python3 modules(?) Assuming pipx is the
> same thing.

You have to install python2's pip. pipx is the same but with virtual
environment isolation.

**Comment by pvuorela** [comment]
> You have to install python2's pip

That's what I thought and that's too much. Looks like Fedora hasn't gotten that available for long time.

**Pull request merged**
